import os

OPENAI_API_KEY = os.environ.get("OPENAI_API_KEY", "")
OPENAI_BASE_URL = os.environ.get("OPENAI_BASE_URL", "")

NEURONPEDIA_API_KEY = os.environ.get("NEURONPEDIA_API_KEY", "")

EXPLANATIONS_EMBEDDING_PATH = os.environ.get("EXPLANATIONS_EMBEDDING_PATH", "")
VECTOR_DB_PATH = os.environ.get("VECTOR_DB_PATH", "")
CLUSTERING_PATH = os.environ.get("CLUSTERING_PATH", "")
SIMILARITIES_PATH = None

EXPLANATIONS_EMBEDDING_PATH_GPT = os.environ.get("EXPLANATIONS_EMBEDDING_PATH_GPT", "")
VECTOR_DB_PATH_GPT = os.environ.get("VECTOR_DB_PATH_GPT", "")
CLUSTERING_PATH_GPT = os.environ.get("CLUSTERING_PATH_GPT", "")
SIMILARITIES_PATH_GPT = None

MAX_RETRIES = 3
BATCH_SIZE = 5
